# CONFIGURACIÓN DEL SERVIDOR
server.port=8080

# CONFIGURACIÓN DE LA BASE DE DATOS (CRUCIAL PARA EL DESPLIEGUE SEGURO)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACIÓN DE JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
#le dice a hibernate que me cree las tablas con las clases que uso
spring.jpa.show-sql=true